const items = [
  {
    id: "001",
    image: "images/chocolate-1.jpg",
    company: "Cadbury Dairy Milk",
    item_name: "Silk Oreo",
    original_price: 1045,
    current_price: 606,
    discount_percentage: 42,
    return_period: 14,
    delivery_date: "24 May 2024",
    rating: {
      stars: 4.5,
      count: 1400,
    },
  },
  {
    id: "002",
    image: "images/chocolate-2.jpg",
    company: "Cadbury Dairy Milk",
    item_name: "Hazel Nut",
    original_price: 2599,
    current_price: 1507,
    discount_percentage: 42,
    return_period: 14,
    delivery_date: "24 May 2024",
    rating: {
      stars: 4.3,
      count: 24,
    },
  },
  {
    id: "003",
    image: "images/chocolate-3.jpg",
    company: "Cadbury Dairy Milk",
    item_name: "Silk Bubbly",
    original_price: 1599,
    current_price: 495,
    discount_percentage: 69,
    return_period: 14,
    delivery_date: "24 May 2024",
    rating: {
      stars: 4.1,
      count: 249,
    },
  },
  {
    id: "004",
    image: "images/chocolate-4.jpg",
    company: "Cadbury Dairy Milk",
    item_name: "Silk Bubbly",
    original_price: 999,
    current_price: 999,
    discount_percentage: 0,
    return_period: 14,
    delivery_date: "24 May 2024",
    rating: {
      stars: 5.0,
      count: 10,
    },
  },
  {
    id: "005",
    image: "images/chocolate-5.jpg",
    company: "Cadbury Dairy Milk",
    item_name: "Silk",
    original_price: 1399,
    current_price: 489,
    discount_percentage: 65,
    return_period: 14,
    delivery_date: "24 May 2024",
    rating: {
      stars: 4.2,
      count: 3500,
    },
  },
  {
    id: "006",
    image: "images/chocolate-6.jpg",
    company: "Amul",
    item_name: "Dark chocolate",
    original_price: 14995,
    current_price: 14995,
    discount_percentage: 0,
    return_period: 14,
    delivery_date: "24 May 2024",
    rating: {
      stars: 0.0,
      count: 0,
    },
  },
  {
    id: "007",
    image: "images/chocolate-7.jpg",
    company: "Cadbury",
    item_name: "Bournville",
    original_price: 1599,
    current_price: 639,
    discount_percentage: 60,
    return_period: 14,
    delivery_date: "24 May 2024",
    rating: {
      stars: 4.2,
      count: 388,
    },
  },
  {
    id: "008",
    image: "images/chocolate-8.jpg",
    company: "Amul",
    item_name: "Fruit and Nut",
    original_price: 285,
    current_price: 142,
    discount_percentage: 50,
    return_period: 14,
    delivery_date: "24 may 2024",
    rating: {
      stars: 4.2,
      count: 5200,
    },
  },
];
